name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install gcc-arm-none-eabi clang-format
    - name: lint check
      run: make lint-check
    - name: compile all projects
      run: make
